BlogApp.Web.UI/Models/ErrorViewModel.cs
namespace BlogApp.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogApp.Web.UI/Areas/Admin/Controllers/BlogCategoryController.cs
using BlogApp.Model.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BlogApp.Dashboard.UI.Controllers
{
    [Area("Admin")]
    public class BlogCategoryController : Controller
    {
        Uri baseUri = new Uri("https://localhost:7005/api");
        HttpClient client;
       
        public BlogCategoryController()
        {

            client = new HttpClient();
            client.BaseAddress = baseUri;
        }
        public IActionResult Index()
        {
            List<BlogCategoryVM> viewModels = new List<BlogCategoryVM>();
            HttpResponseMessage response = client.GetAsync(baseUri + "/BlogCategories").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                viewModels = JsonConvert.DeserializeObject<List<BlogCategoryVM>>(data);
            }

            return View(viewModels);
         
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(BlogCategoryVM viewModel)
        {
            string Data = JsonConvert.SerializeObject(viewModel);
            StringContent content = new StringContent(Data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(baseUri + "/BlogCategories", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BlogApp.Web.UI/Areas/Admin/Controllers/HomeController.cs
using BlogApp.Web.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogApp.Web.UI.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogApp.Web.UI/Areas/SimpleUser/Controllers/CreateUserController.cs
using BlogApp.Model.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BlogApp.Web.UI.Areas.SimpleUser.Controllers
{
    [Area("SimpleUser")]
    public class CreateUserController : Controller
    {
        //https://localhost:7005/api/UserRegistrations/register
        Uri baseUri = new Uri("https://localhost:7005/api");
        HttpClient client;
        public CreateUserController()
        {
            client = new HttpClient();
            client.BaseAddress = baseUri;
        }
        public IActionResult UserRegistration()
        {
            return View();
        }
        [HttpPost]
        public IActionResult UserRegistration(UserRegistrationVM viewModel)
        {
            string Data = JsonConvert.SerializeObject(viewModel);
            StringContent content = new StringContent(Data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(baseUri + "/UserRegistrations/register", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Login", "LoginUser");
            }
            return View();
        }



    }
}

BlogApp.Web.UI/Areas/SimpleUser/Controllers/HomeController.cs
using BlogApp.Web.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogApp.Web.UI.Areas.SimpleUser.Controllers
{
    [Area("SimpleUser")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult TestPage()
        {
            return View();
        }
        public RedirectResult Privacy()
        {
            return Redirect("https://google.com");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogApp.Web.UI/Areas/SimpleUser/Controllers/LoginUserController.cs
using BlogApp.Model.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BlogApp.Web.UI.Areas.SimpleUser.Controllers
{
    [Area("SimpleUser")]
    //https://localhost:7005/api/UserLogin/login
    public class LoginUserController : Controller
    {
        Uri baseUri = new Uri("https://localhost:7005/api");
        HttpClient client;

        public LoginUserController()
        {
            client = new HttpClient();
            client.BaseAddress = baseUri;
        }
        public IActionResult Login()
        {

            //Session["UserID"] = obj.UserId.ToString();
            //Session["UserName"] = obj.UserName.ToString();
            //return RedirectToAction("UserDashBoard");
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserLoginVM userLoginModel)
        {
            string Data = JsonConvert.SerializeObject(userLoginModel);
            StringContent content = new StringContent(Data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(baseUri + "/UserLogin", content).Result;
            if (response.IsSuccessStatusCode)
            {
                List<string> roleList = new List<string>();
                roleList = GetAllRole(userLoginModel.UserName);
                //string r = "ddd";
                //bool isExist = roleList.Find(r);

                //var role1=roleList.Where(x => x.Equals("Super Admin"));
                bool role1 = roleList.Contains("Super Admin");
                bool role2 = roleList.Contains("Admin");
                // bool role2=roleList.Where(x => x.Equals("Admin")).First();
                // var role3=roleList.Find("Super Admin")



                if (role1 != null)
                {
                    return RedirectToAction("Index","Home",new {area= "Admin" });
                }
                else if (role2 != null)
                {
                    return Redirect("http://localhost:5160/Home/Index");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

                // return RedirectToLocal(returnUrl);

                //http://localhost:5160/

                // return RedirectToAction("TestPage", "Home");
            }
            return View();
        }

        private List<string> GetAllRole(string username)
        {

            List<string> roles = new List<string>();
            HttpResponseMessage response = client.GetAsync(baseUri + "/UserLogin/" + username).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                roles = JsonConvert.DeserializeObject<List<string>>(data);
            }

            return roles;
        }

    }
}

BlogApp.Web.UI/Areas/Admin/Views/BlogCategory/Create.cshtml
@model BlogCategoryVM
@{
   ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="CategoryTitle"></label>
			<input asp-for="CategoryTitle" class="form-control" />
			<span asp-validation-for="CategoryTitle" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="CategoryDescription"></label>
			<input asp-for="CategoryDescription" class="form-control" />
			<span asp-validation-for="CategoryDescription" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-area="Admin" asp-controller="BlogCategories" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BlogApp.Web.UI/Areas/Admin/Views/BlogCategory/Index.cshtml
@model IEnumerable<BlogCategoryVM>
@{
   ViewData["Title"] = "Home Page";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6 ">
            <h2 class="text-primary">Category List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-area="Admin" asp-controller="BlogCategory" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Category
			</a>
		</div>
	</div>
    <br /><br />
     
<table class="table table-bordered table-striped table-sm" style="width:100%">
    <thead>
        <tr>
            <th>
                 Title
			</th>
            <th>
                Description
			</th>
            <th></th>
		</tr>
	</thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="20%">
                    @obj.CategoryTitle
				</td>
                <td width="30%">
                    @obj.CategoryDescription
				</td>
                <td>
                    <div class="w-15  btn-group" role="group">
                        <a asp-area="Admin" asp-controller="BlogCategories" asp-action="Edit" asp-route-id="@obj.BlogCategoryId"
                        class="btn btn-sm btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-area="Admin" asp-controller="BlogCategories" asp-action="Delete" asp-route-id="@obj.BlogCategoryId"
                        class="btn btn-sm btn-danger mx-1"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
				</td>
			</tr>
        }
    </tbody>

</table>

</div>

BlogApp.Web.UI/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

  <!-- Page wrapper  -->
      <!-- ============================================================== -->
      <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">Dashboard</h4>
              <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                      Library
                    </li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
          <!-- ============================================================== -->
          <!-- Sales Cards  -->
          <!-- ============================================================== -->
          <div class="row">
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-cyan text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-view-dashboard"></i>
                  </h1>
                  <h6 class="text-white">Dashboard</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-4 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-success text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-chart-areaspline"></i>
                  </h1>
                  <h6 class="text-white">Charts</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-warning text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-collage"></i>
                  </h1>
                  <h6 class="text-white">Widgets</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-danger text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-border-outside"></i>
                  </h1>
                  <h6 class="text-white">Tables</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-info text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-arrow-all"></i>
                  </h1>
                  <h6 class="text-white">Full Width</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-md-6 col-lg-4 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-danger text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-receipt"></i>
                  </h1>
                  <h6 class="text-white">Forms</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-info text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-relative-scale"></i>
                  </h1>
                  <h6 class="text-white">Buttons</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-cyan text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-pencil"></i>
                  </h1>
                  <h6 class="text-white">Elements</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-success text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-calendar-check"></i>
                  </h1>
                  <h6 class="text-white">Calnedar</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                <div class="box bg-warning text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-alert"></i>
                  </h1>
                  <h6 class="text-white">Errors</h6>
                </div>
              </div>
            </div>
            <!-- Column -->
          </div>
          <!-- ============================================================== -->
          <!-- Sales chart -->
          <!-- ============================================================== -->
         
          <!-- ============================================================== -->
          <!-- Sales chart -->
          <!-- ============================================================== -->
          <!-- ============================================================== -->
          <!-- Recent comment and chats -->
          <!-- ============================================================== -->
         
          <!-- ============================================================== -->
          <!-- Recent comment and chats -->
          <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
          All Rights Reserved by Shamsul Arifin
          
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
      </div>

BlogApp.Web.UI/Areas/SimpleUser/Views/CreateUser/UserRegistration.cshtml
@model UserRegistrationVM

@{
    ViewData["Title"] = "CreateUser";
}


<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/css/main.css">

<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(~/ThemeTemplate/FormTemplate/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						Registration
					</span>
				</div>

				<form asp-action="CreateUser" class="login100-form validate-form">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>



					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input asp-for="UserName" class="input100" type="text" name="username" placeholder="Enter username">
						<span asp-validation-for="UserName" class="focus-input100 text-danger"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-26" data-validate="Email is required">
						<span class="label-input100">Email</span>
						<input asp-for="Email" class="input100" type="text" name="email" placeholder="Enter Email">
						<span asp-validation-for="Email" class="focus-input100 text-danger"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input asp-for="Password" type="password" placeholder="Enter password">
						<span  asp-validation-for="Password" class="focus-input100"></span>
					</div>

				

					<div class="container-login100-form-btn">
						
						<button type="submit" class="login100-form-btn">
							Register
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/bootstrap/js/popper.js"></script>
	<script src="~/ThemeTemplate/FormTemplate/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/moment.min.js"></script>
	<script src="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/js/main.js"></script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogApp.Web.UI/Areas/SimpleUser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        
    </p>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogApp.Web.UI/Areas/SimpleUser/Views/Home/TestPage.cshtml
@{
    ViewData["Title"] = "TestPage";
}

<h1>TestPage</h1>

BlogApp.Web.UI/Areas/SimpleUser/Views/LoginUser/Login.cshtml
@model UserLoginVM

@{
    ViewData["Title"] = "Login";
}

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/ThemeTemplate/FormTemplate/css/main.css">


<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(~/ThemeTemplate/FormTemplate/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						Sign In
					</span>
				</div>

				<form asp-action="Login" class="login100-form validate-form">
					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input asp-for="UserName"  class="input100" type="text" name="username" placeholder="Enter username">
						<span asp-validation-for="UserName" class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input asp-for="Password"  type="password"  placeholder="Enter password">
						<span asp-validation-for="Password" class="focus-input100"></span>
					</div>

					<div class="flex-sb-m w-full p-b-30">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/bootstrap/js/popper.js"></script>
	<script src="~/ThemeTemplate/FormTemplate/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/moment.min.js"></script>
	<script src="~/ThemeTemplate/FormTemplate/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="~/ThemeTemplate/FormTemplate/js/main.js"></script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}